# Generated by Django 4.2.1 on 2023-05-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='urun ismi')),
                ('content', models.TextField(max_length=500, verbose_name='urun aciklamasi')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('stock_count', models.BigIntegerField(verbose_name='stok_adedi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='urun fiyati')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
